[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dbex"
version = "0.1"
dependencies = [
    "h5py",
    "scipy",
    "matplotlib",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["dbex*"]